type ComponentDefinitionForTs = {
  uuid: string;
  type: string;
  properties: Array<{ path: string; type: string; tooltip?: string; enumValues?: string[] }>;
};

type NodeDefinitionForTs = {
  uuid: string;
  properties: Array<{ path: string; type: string; tooltip?: string; enumValues?: string[] }>;
};

function toSafeIdentifier(raw: string): string {
  const safe = raw
    .replace(/[^a-zA-Z0-9_]+/g, "_")
    .replace(/^_+/, "")
    .slice(0, 80);
  return safe.length > 0 ? safe : "Type";
}

export function buildTsForComponent(def: ComponentDefinitionForTs): string {
  const safeTypeName = toSafeIdentifier(def.type);

  const lines: string[] = [];
  lines.push("// Auto-generated by cocos-skill definitions");
  lines.push(`// Component UUID: ${def.uuid}`);
  lines.push(`// Component Type: ${def.type}`);
  lines.push("");

  const paths = def.properties.map((p) => p.path).sort((a, b) => a.localeCompare(b));

  lines.push(`export type ${safeTypeName}_PropertyPath =`);
  if (paths.length === 0) {
    lines.push("  | never;");
  } else {
    for (const p of paths) {
      lines.push(`  | ${JSON.stringify(p)}`);
    }
    lines.push(";");
  }

  lines.push("");
  lines.push(`export type ${safeTypeName}_PropertyTypeMap = {`);
  for (const prop of def.properties) {
    const commentParts: string[] = [];
    if (prop.tooltip) commentParts.push(`tooltip: ${prop.tooltip}`);
    if (prop.enumValues && prop.enumValues.length > 0) commentParts.push(`enum: [${prop.enumValues.join(", ")}]`);
    if (commentParts.length > 0) {
      lines.push(`  // ${commentParts.join(" | ")}`);
    }
    lines.push(`  ${JSON.stringify(prop.path)}: ${JSON.stringify(prop.type)};`);
  }
  lines.push("};");

  return lines.join("\n");
}

export function buildTsForNode(def: NodeDefinitionForTs): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cocos-skill definitions");
  lines.push(`// Node UUID: ${def.uuid}`);
  lines.push("");

  const paths = def.properties.map((p) => p.path).sort((a, b) => a.localeCompare(b));

  lines.push("export type NodePropertyPath =");
  if (paths.length === 0) {
    lines.push("  | never;");
  } else {
    for (const p of paths) {
      lines.push(`  | ${JSON.stringify(p)}`);
    }
    lines.push(";");
  }

  lines.push("");
  lines.push("export type NodePropertyTypeMap = {");
  for (const prop of def.properties) {
    const commentParts: string[] = [];
    if (prop.tooltip) commentParts.push(`tooltip: ${prop.tooltip}`);
    if (prop.enumValues && prop.enumValues.length > 0) commentParts.push(`enum: [${prop.enumValues.join(", ")}]`);
    if (commentParts.length > 0) {
      lines.push(`  // ${commentParts.join(" | ")}`);
    }
    lines.push(`  ${JSON.stringify(prop.path)}: ${JSON.stringify(prop.type)};`);
  }
  lines.push("};");

  return lines.join("\n");
}
